### ISSUE TITLE
Java Exception with example file

### ISSUE THREAD

**Issue by joaoe** [bioinform/varsim#107]
Hello.

While runnign VarSim with [All_20160601.vcf.gz](http://ftp.ncbi.nih.gov/snp/organisms/human_9606_b147_GRCh37p13/VCF/All_20160601.vcf.gz) the program crashes

```
INFO [main] (VCFparser.java:45): Reading All_20160601.vcf.gz
FATAL [main] (VCFparser.java:662): Cannot cast java.lang.Boolean to [Ljava.lang.String;
1    10019    rs775809821    TA    T    .    .    RS=775809821;RSPOS=10020;dbSNPBuildID=144;SSR=0;SAO=0;VP=0x05000002000500000200
0200;GENEINFO=DDX11L1:100287102;WGT=1;VC=DIV;R5;ASP
java.lang.ClassCastException: Cannot cast java.lang.Boolean to [Ljava.lang.String;
    at java.lang.Class.cast(Class.java:3369)
    at com.bina.varsim.types.VCFInfo$VCFInfoElement.<init>(VCFInfo.java:75)
    at com.bina.varsim.types.VCFInfo.<init>(VCFInfo.java:30)
    at com.bina.varsim.util.VCFparser.processLine(VCFparser.java:309)
    at com.bina.varsim.util.VCFparser.parseLine(VCFparser.java:659)
    at com.bina.varsim.tools.simulation.RandVCF2VCF.countVariants(RandVCF2VCF.java:102)
    at com.bina.varsim.tools.simulation.RandVCF2VCF.run(RandVCF2VCF.java:281)
    at com.bina.varsim.VarSim.runVarSimTool(VarSim.java:62)
    at com.bina.varsim.VarSim.run(VarSim.java:112)
    at com.bina.varsim.VarSim.main(VarSim.java:30)
```
The culprit seems to be [this line](https://github.com/bioinform/varsim/blob/master/src/main/java/com/bina/varsim/types/VCFInfo.java#L75) where a Boolean is being assigned to a String field, when creating VCFInfoElement classes for the `R5` and `ASP` fields.

We're using OpenJDK 1.8, could that be the problem ?

**Comment by yunfeiguo** [comment]
Hi,

I tested the failing input with latest VarSim under JRE 1.8.0_60-b27 and it worked fine. Could you try that? Thanks.

**Comment by joaoe** [comment]
This is the one we have installed
```
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
(which is the default ubuntu one).
Is the version you used Oracle Java or OpenJDK ? 
Thank you.

**Comment by yunfeiguo** [comment]
It is Oracle java. Thanks.

**Comment by joaoe** [comment]
Ok, I try it later and then report.

**Comment by joaoe** [comment]
It worked with Oracle Java just fine. Seems like a potential bug to report to the OpenJDK project. Is OpenJDK something you support or not ? Asking since it's the default java runtime that comes with most linux distributions nowadays.

**Comment by yunfeiguo** [comment]
Thanks for reporting back! Based on this [post](http://stackoverflow.com/questions/22358071/differences-between-oracle-jdk-and-open-jdk-and-garbage-collection), OpenJDK and Oracle JDK should be almost the same. So what works in one case should also work in another. For the specific problem you had, it looks more like a bug in OpenJDK as you have suggested, rather than compatibility issue. Thank you.

**Comment by jazberna1** [comment]
Hello,

I am facing the same error. Is there a specific version of Oracle or Open JDK that is known to work with varsim-0.7.1 ? 

Many thanks
Jorge

**Comment by yunfeiguo** [comment]
Hi @jazberna1 please use Oracle JDK 1.8 or above, thanks.
