### ISSUE TITLE
adjusting wiggle parameter

### ISSUE THREAD

**Issue by kunalkathuria** [bioinform/varsim#117]
Hi,

I was wondering how I can adjust the wiggle parameter in vcf comparison.Can I set it from command line? If not, can I change it in VCFcompare.java and recompile somehow? How would I do this? Thank you very much!

**Comment by kunalkathuria** [comment]
Never mind, found it in command line options in java -jar vcfcompare...

**Comment by yunfeiguo** [comment]
Hi,

`-wig` followed by an integer can be used to set wiggle parameter in a command line. there is no need to recompile.

**Comment by kunalkathuria** [comment]
Thank you!
