### ISSUE TITLE
TypeError: run_randvcf() takes exactly 7 arguments (15 given)

### ISSUE THREAD

**Issue by iranmdl** [bioinform/varsim#134]
Hi,

I'm having the following error when trying to run `varsim_somatic.py` script:

```
Traceback (most recent call last):
  File "varsim_somatic.py", line 229, in <module>
    varsim_somatic_main()
  File "varsim_somatic.py", line 132, in varsim_somatic_main
    os.path.realpath(args.reference.name), args.som_prop_het)])
TypeError: run_randvcf() takes exactly 7 arguments (15 given)
```

This is the command I'm using:

`python varsim_somatic.py --reference hs37d5.fa --id cosmic --som_num_snp 10000 --cosmic_vcf cosmic.vcf.gz --normal_vcf out/simu.truth.vcf --nlanes 1 --total_coverage 1 --simulator art --simulator_executable /shared/tools/src/art_bin_MountRainier/art_illumina --out_dir som_out --log_dir som_log --sv_insert_seq insert_seq.txt`

Checking the `run_randvcf` function in `varsim.py` script, we can see that it takes exactly 7 arguments:

`def run_randvcf(sampling_vcf, out_vcf_fd, log_file_fd, seed, sex, randvcf_options, reference)
`

But in `varsim_somatic.py` script, the function is called with the following arguments:

```
monitor_processes([run_randvcf(os.path.realpath(args.cosmic_vcf), rand_vcf_stdout, rand_vcf_stderr,
args.seed, args.sex, args.som_num_snp, args.som_num_ins, args.som_num_del, args.som_num_mnp,
args.som_num_complex, 0, args.som_min_length_lim, args.som_max_length_lim, os.path.realpath(args.reference.name), args.som_prop_het)])
```

Any help will be appreciated :)

**Comment by marghoob** [comment]
Thanks @iranmdl , this fix is already being tested in the bugfixes-0.8.0 branch (see https://github.com/bioinform/varsim/pull/131). Please give the branch a try to see if it works for you.

**Comment by iranmdl** [comment]
Thank you @marghoob , that issue has been fixed in the branch. 
But now I get another error when running `varsim_somatic.py`:
`NameError: global name 'RandVCFOptions' is not defined`

`RandVCFOptions` is a class object in `varsim.py`, not imported to `varsim_somatic.py`

**Comment by yunfeiguo** [comment]
Hi @iranmdl 
this problem has been fixed, thanks!

**Comment by marghoob** [comment]
@iranmdl could you please confirm that this is no longer an issue for you? thanks!

**Comment by iranmdl** [comment]
@marghoob The issue has been fixed and now is working perfectly. 
Thank you!
