### ISSUE TITLE
TypeError: sequence item 29: expected string, NoneType found

### ISSUE THREAD

**Issue by haoziyeung** [bioinform/varsim#147]
Hi,@yunfeiguo,i'm using varsim to get a pair simulated fastq within a certain interval file,like below:

`python /gpfs/users/yanghao/software/varsim_run/varsim_multi.py --regions Euler_MSKCC_actionable_cancer_original.sort.bed --sv_insert_seq /gpfs/users/yanghao/software/varsim_run/insert_seq.txt --sv_dgv /gpfs/users/yanghao/software/varsim_run/GRCh37_hg19_supportingvariants_2013-07-23.txt --reference /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta --vc_num_snp 3000000 --vc_num_ins 100000 --vc_num_del 100000 --vc_num_mnp 50000 --vc_num_complex 50000 --sv_num_ins 0 --sv_num_del 0 --sv_num_dup 0 --sv_num_inv 0 --sv_percent_novel 0 --vc_percent_novel 0.01 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 --sv_max_length_lim 1000000 --nlanes 1 --total_coverage 1000 --simulator_executable /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina --out_dir 1k_mskcc --simulator art --log_to_stderr --loglevel debug --samples sample1`

and get error message:

`INFO 2018-02-07 14:22:47,791 gen_restricted_reference Lifted over the reference to 1k_mskcc/restricted/ref.fa
INFO 2018-02-07 14:22:47,811 varsim_multi         Simulating sample sample1 in 1k_mskcc/sample1
Traceback (most recent call last):
  File "/gpfs/users/yanghao/software/varsim_run/varsim_multi.py", line 256, in <module>
    samples_random=args.samples_random)
  File "/gpfs/users/yanghao/software/varsim_run/varsim_multi.py", line 81, in varsim_multi
    run_randvcf(sampling_vcf, randvcf_out, randvcf_log, sample_seed, sex, randvcf_options, reference).wait()
  File "/gpfs/users/yanghao/software/varsim_run/varsim.py", line 245, in run_randvcf
    logger.info("Executing command " + " ".join(rand_vcf_command))
TypeError: sequence item 29: expected string, NoneType found
`

can you tell me what's going on? thanks a lot.

**Comment by haoziyeung** [comment]
in fact , i want to simulate 1000x,2000x,5000x data,so i don't want to use `varsim.py`,because it will generate  variants on entire genome,maybe too slow in this case.

**Comment by haoziyeung** [comment]
Let me make myself clearly,i want to generate simulated somatic mutation data within a certain interval, thanks

**Comment by haoziyeung** [comment]
Finally,i get the correct command,like below:
`python /gpfs/users/yanghao/software/varsim_run/varsim_multi.py --regions ../Euler_MSKCC_actionable_cancer_original.sort.bed --sv_insert_seq /gpfs/users/yanghao/software/varsim_run/insert_seq.txt --sv_dgv /gpfs/users/yanghao/software/varsim_run/GRCh37_hg19_supportingvariants_2013-07-23.txt --reference /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta --vc_num_snp 3000000 --vc_num_ins 100000 --vc_num_del 100000 --vc_num_mnp 0 --vc_num_complex 0 --sv_num_ins 0 --sv_num_del 0 --sv_num_dup 0 --sv_num_inv 0 --sv_percent_novel 0 --vc_percent_novel 0.01 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 --sv_max_length_lim 1000000 --nlanes 1 --total_coverage 10 --simulator_executable /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina --out_dir . --simulator art --log_to_stderr --loglevel debug --sampling_vcf /gpfs/users/yanghao/database/ncbi/dbsnp/All_20170710.vcf.gz`

it's because your manual in http://bioinform.github.io/varsim/ have some error,you forget use --sampling_vcf

and i found --total_coverage 1 should be --total_coverage 30

**Comment by jayaramanp** [comment]
Hello @haoziyeung, were you able to simulate fastq data using varsim_multi.py?

I used the command you have up here and I'm getting having issues..figured before I check with @yunfeiguo i'll ask you if you were ever able to generate fastq using varsim_multi.py?
