### ISSUE TITLE
dbSNP 141 file is unavailable

### ISSUE THREAD

**Issue by zwm0502** [bioinform/varsim#161]
Hello,
(1)The file dbSNP 141 file [All.vcf.gz]  is unavailable now.
(2)Could the varsim simulate other genomes like Ecoli K12? I want to simulate a ecoli genome and simulate reads from the new genome by another simulator rather than ART. How could I do this ?
(3)./varsim.py -h
Traceback (most recent call last):
  File "./varsim.py", line 17, in <module>
    from liftover_restricted_vcf_map import lift_vcfs, lift_maps
  File "/share/home/user/wmzhang/software/varsim_run/liftover_restricted_vcf_map.py", line 6, in <module>
    import vcf
ImportError: No module named vcf  
What does the error above mean?
Thank you very much!

**Comment by yunfeiguo** [comment]
Hi @zwm0502 

Thanks for the feedback. 

* Please download dbsnp with this URL: ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz
* VarSim right now does not support non-human genomes. We hope to make varsim more general later on, but there is no guarantee when this will happen.
* please install pyvcf: `pip install pyvcf`
