### ISSUE TITLE
WARN [main] (VCFparser.java:189): Unrecognized phasing '.'.

### ISSUE THREAD

**Issue by LeeNicha** [bioinform/varsim#162]
Hi, I got the following error when I tried to simulate normal sample with germline mutations.
----------------------------------------------------------------------------------------------------
File "varsim.py", line 721, in <module>
    disable_vcf2diploid=args.disable_vcf2diploid)
  File "varsim.py", line 356, in varsim_main
    processes = monitor_processes(processes)
  File "varsim.py", line 141, in monitor_processes
    raise Exception('Aborting... Please check log for details.')
Exception: Aborting... Please check log for details.
----------------------------------------------------------------------------------------------------
[RandVCF2VCF.tar.gz](https://github.com/bioinform/varsim/files/1851186/RandVCF2VCF.tar.gz)

This is my command:
python varsim.py --reference ~/program/automated_wxs_pipeline/database/human_g1k_v37.fasta --vc_in_vcf All.vcf.gz --sv_insert_seq insert_seq.txt --sv_dgv GRCh37_hg19_supportingvariants_2016-05-15.txt --id normal --read_length 101 --vc_num_snp 3000000 --sv_num_ins 0 --sv_num_del 0 --sv_num_dup 0 --sv_num_inv 0 --mean_fragment_size 350 --sd_fragment_size 50 --nlanes 5 --total_coverage 100 --simulator_executable ART/art_bin_VanillaIceCream/art_illumina --out_dir germline/out --log_dir germline/log --work_dir germline/work --simulator art

Thank you in advance for your kind response.

**Comment by yunfeiguo** [comment]
Could you try latest release?
https://github.com/bioinform/varsim/releases/tag/v0.8.3

**Comment by LeeNicha** [comment]
Yes. but I found another error!!
This is my command
./varsim.py

![screen shot 2561-04-09 at 16 40 48](https://user-images.githubusercontent.com/24719780/38490987-ce3be012-3c14-11e8-9823-e400eea322ad.png)

Thank you in advance for your kind response.

**Comment by LeeNicha** [comment]
This is the output.


Thank you

**Comment by yunfeiguo** [comment]
Can't see anything.

**Comment by yunfeiguo** [comment]
![image](https://user-images.githubusercontent.com/7737294/38581206-fceda952-3cc0-11e8-98fc-994d516bfa1d.png)
you mean this one?

Could you run `java -version` in your *terminal* (command line)?

**Comment by LeeNicha** [comment]
I knew why shown this error. Becurse I installed only JDK, but it needs JSE
to run the program.

Thankyou.



ในวันที่ พ. 11 เม.ย. 2018 03:14 Yunfei Guo <notifications@github.com>
เขียนว่า:

**Comment by yunfeiguo** [comment]
👍  let me know if you have additional questions.

**Comment by LeeNicha** [comment]
Ok and Thank you for your help
