### ISSUE TITLE
run_randvcf: AttributeError: 'NoneType' object has no attribute 'wait'

### ISSUE THREAD

**Issue by genomics-geek** [bioinform/varsim#186]
I have been evaluating varsim, but I have been trying to figure out how to run `varsim_multi` to generate simulated data for exomes and panels.  I have had trouble getting it to run.  Below are the details of the error message and the `varsim_multi` command I submit.  Thanks in advance for your help.

The error traceback:
```
Traceback (most recent call last):
  File "varsim_multi.py", line 290, in <module>
    samples_random=args.samples_random)
  File "varsim_multi.py", line 98, in varsim_multi
    run_randvcf(sampling_vcf, randvcf_out, randvcf_log, sample_seed, sex, randvcf_options, reference).wait()
AttributeError: 'NoneType' object has no attribute 'wait'
```

Version of varsim: 0.8.4
Python: 2.7.13

Here is my command: 
```
pyenv/bin/python varsim_multi.py \
  --regions files/regions.sorted.bed \
  --reference /references/GRCh37/human_g1k_v37.fasta \
  --sampling_vcf files/00-All.vcf.gz \
  --vc_num_snp 50000 \
  --vc_num_ins 1600 \
  --vc_num_del 1600 \
  --vc_num_mnp 0 \
  --vc_num_complex 0 \
  --vc_percent_novel 0.01 \
  --vc_min_length_lim 0 \
  --vc_max_length_lim 49 \
  --nlanes 1 \
  --total_coverage 100 \
  --simulator_executable files/ART/art_bin_MountRainier/art_illumina \
  --out_dir out \
  --simulator art \
  --simulator_options "-p -l 100 -m 350 -s 50" \
  --samples_random 1 \
  --loglevel debug
```

**Comment by yunfeiguo** [comment]
Hi thanks for reporting, this will be fixed soon.

**Comment by genomics-geek** [comment]
Thank you very much @yunfeiguo!

Also, I have been trying to read through the documentation and repo to better understand how to use varsim_multi. 

Is that command appropriate for generating simulated exome data? Thanks!

**Comment by yunfeiguo** [comment]
yes, but note that for exome, the capture/coverage/amplification biases are not simulated.

**Comment by genomics-geek** [comment]
Thank you for the information. That is fine for my purposes.

If I use the vcfs parameter, is that how I can “spike” in variants?

**Comment by yunfeiguo** [comment]
`BAMSurgeon` can give you a more empirical simulation with biases embedded in BAM. But please consult `BAMSurgeon`'s documentation for more details.

For your second question, yes.

**Comment by genomics-geek** [comment]
Perfect. Thanks, this has been very helpful.

**Comment by yunfeiguo** [comment]
No problem. Please pull from `master` (or download https://github.com/bioinform/varsim/archive/master.zip ) and run `./build.sh` inside varsim folder to get the latest version. Thanks.
