### ISSUE TITLE
Varsim build.sh error st RTG tools jar step

### ISSUE THREAD

**Issue by jayaramanp** [bioinform/varsim#194]
Hello @yunfeiguo , 
I'm trying to use Varsim to simulate fastq for a targeted region. I have however encountered little to no success yet and need help. 

I recently went through some of the issues which mentioned pulling from the master branch and running:

    ./build.sh

I did that recently and I encountered errors leading to a failed BUILD. Here is the build command I used:

 Results:
 Tests run: 97, Failures: 0, Errors: 0, Skipped: 1

[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ varsim ---
[INFO] 
[INFO] --- maven-shade-plugin:1.7.1:shade (VarSim) @ varsim ---
[INFO] Including com.github.samtools:htsjdk:jar:2.14.3 in the shaded jar.
[INFO] Including org.apache.commons:commons-jexl:jar:2.1.1 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.1 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.1.4 in the shaded jar.
[INFO] Including org.apache.commons:commons-compress:jar:1.4.1 in the shaded jar.
[INFO] Including org.tukaani:xz:jar:1.5 in the shaded jar.
[INFO] Including gov.nih.nlm.ncbi:ngs-java:jar:1.2.4 in the shaded jar.
[INFO] Including org.jgrapht:jgrapht-core:jar:1.0.1 in the shaded jar.
[INFO] Including args4j:args4j:jar:2.33 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:17.0 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.3.1 in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.6.1 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.10 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.2.3 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.2.3 in the shaded jar.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.033 s
[INFO] Finished at: 2019-04-25T14:40:39-04:00
[INFO] ------------------------------------------------------------------------
+ git submodule init
+ git submodule update
+ pushd rtg-tools
/Public/varsim/master/varsim/rtg-tools /Public/varsim/master/varsim
+ rm -rf 'rtg-tools-*'
+ /Public/varsim/master/varsim/opt/apache-ant-1.9.13/bin/ant zip-nojre
Buildfile: build.xml

init:

rtg-vcs-info:
     [echo] Current build revision is bdba5ea

zip-init:

zip-jars:

init:

compile-src:

rtg-vcs-info:

set-rtg-build-version:

BUILD FAILED
/resnfs03/DGD/public/varsim/master/varsim/rtg-tools/build.xml:356: The following error occurred while executing this line:
/resnfs03/DGD/public/varsim/master/varsim/rtg-tools/build.xml:266: The following error occurred while executing this line:
/resnfs03/DGD/public/varsim/master/varsim/rtg-tools/build.xml:239: Problem: failed to create task or type local
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

 Total time: 3 seconds

**Comment by yunfeiguo** [comment]
Hi @jayaramanp let me take a look, thanks!

**Comment by yunfeiguo** [comment]
I did find and then fixed a typo in `build.sh`, could you `git pull` and try again? Also, do you have your own `ant` on `PATH`?

**Comment by jayaramanp** [comment]
hi @yunfeiguo I'll git pull right now.. I don't have my own 
`ant` in `PATH` why? do you need me to have my own `ant`?

**Comment by jayaramanp** [comment]
hi @yunfeiguo it still fails around the RTG-tools step.



+ git submodule init
+ git submodule update
+ pushd rtg-tools
/Public/varsim/master/varsim/rtg-tools /Public/varsim/master/varsim
+ rm -rf 'rtg-tools-*'
+ /Public/varsim/master/varsim/opt/apache-ant-1.9.13/bin/ant zip-nojre
Buildfile: build.xml

init:

rtg-vcs-info:
     [echo] Current build revision is bdba5ea

zip-init:

zip-jars:

init:

compile-src:

rtg-vcs-info:

set-rtg-build-version:

BUILD FAILED
/resnfs03/DGD/public/varsim/master/varsim/rtg-tools/build.xml:356: The following error occurred while executing this line:
/resnfs03/DGD/public/varsim/master/varsim/rtg-tools/build.xml:266: The following error occurred while executing this line:
/resnfs03/DGD/public/varsim/master/varsim/rtg-tools/build.xml:239: Problem: failed to create task or type local
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.


Total time: 2 seconds

**Comment by jayaramanp** [comment]
> I did find and then fixed a typo in `build.sh`, could you `git pull` and try again? Also, do you have your own `ant` on `PATH`?

i think I might be using my own ant
`$ ant -version`
`Apache Ant version 1.7.1 compiled on January 20 2016`

**Comment by jayaramanp** [comment]
Okay the build was successful. i'll try running it now!

**Comment by yunfeiguo** [comment]
ok, great!
