### ISSUE TITLE
Invalid literal for float - while parsing dgv to vcf

### ISSUE THREAD

**Issue by jayaramanp** [bioinform/varsim#196]
Hello @yunfeiguo 

I'm trying to run varsim_multi.py

here is the command I used: (Pyenv python 2.7.8)
`python /Public/varsim/master/varsim/varsim_multi.py --regions /DGD/Research/ConsPanel_RD/SIM/CONS.bed --reference /DGD/clin-air/references/GRCh37/human_g1k_v37.fasta --sampling_vcf /DGD/Research/ConsPanel_RD/SIM/BAMSURGEONSIM/LC_regions.variants.vcf.gz --vc_num_snp 100 --vc_num_ins 60 --sv_insert_seq /Public/varsim/0.8.3/insert_seq.txt --sv_dgv GRCh37_hg19_variants_2016-05-15.txt --vc_num_del 60 --vc_num_mnp 0 --vc_num_complex 0 --vc_percent_novel 0.01 --vc_min_length_lim 0 --vc_max_length_lim 49 --nlanes 1 --total_coverage 600 --simulator_executable /Public/varsim/master/varsim/opt/ART/art_bin_VanillaIceCream/art_illumina --out_dir out --simulator art --simulator_options "-p -l 100 -m 350 -s 50" --samples_random 1 --loglevel debug`

it seems to require a few files:
insert_seq - same file as in quickstart.sh
dgv - this file http://dgv.tcag.ca/dgv/docs/GRCh37_hg19_variants_2016-05-15.txt
simulator options - "-p -l 100 -m 350 -s 50"

and I get the following error, what am I doing wrong?

Traceback (most recent call last):
  File "/Public/varsim/master/varsim/varsim_multi.py", line 290, in <module>
    samples_random=args.samples_random)
  File "/Public/varsim/master/varsim/varsim_multi.py", line 111, in varsim_multi
    _, [restricted_sampled_dgv_vcf] = gen_restricted_ref_and_vcfs(reference, [sampled_dgv_vcf], regions, [], os.path.join(sample_dir, "restricted_randdgvvcf"), flank=0)
  File "/resnfs03/DGD/public/varsim/master/varsim/generate_small_test_ref.py", line 123, in gen_restricted_ref_and_vcfs
    generated_vcfs.append(gen_restricted_vcf(invcf, regions, outvcf, restricted_fasta, samples, flank, short_contig_names))
  File "/resnfs03/DGD/public/varsim/master/varsim/generate_small_test_ref.py", line 80, in gen_restricted_vcf
    for record in records:
  File "/home/jayaramanp/.pyenv/versions/DGDShield-2.7.8/lib/python2.7/site-packages/vcf/parser.py", line 586, in next
    samples = self._parse_samples(row[9:], fmt, record)
  File "/home/jayaramanp/.pyenv/versions/DGDShield-2.7.8/lib/python2.7/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: invalid literal for float(): 3|3

**Comment by yunfeiguo** [comment]
could you provide us with a minimal subset of `/DGD/Research/ConsPanel_RD/SIM/BAMSURGEONSIM/LC_regions.variants.vcf.gz` to reproduce this error?

**Comment by yunfeiguo** [comment]
another simple thing to is `zgrep '3|3' /DGD/Research/ConsPanel_RD/SIM/BAMSURGEONSIM/LC_regions.variants.vcf.gz` to see what line is causing this issue.

**Comment by jayaramanp** [comment]
Thank you @yunfeiguo it was that vcf file.. it missed a header line.. my bad!
I was able to generate fastq data for it. I'll test that fastq now!
Thank you for your help with this.. 


is there a way I can avoid using DGV or insert_seq.txt?

**Comment by yunfeiguo** [comment]
yeah, you can remove the `--sv_dgv` and `--sv_insert_seq` options.
