### ISSUE TITLE
Somatic read generation

### ISSUE THREAD

**Issue by MagdalenaMu** [bioinform/varsim#201]
Dear all,

I am currently generating reads for normal / tumor comparison and I came across the issue that for the somatic simulation, in case I don't specify how many insertions and deletions I want, VarSim ends up generating around 500 indels (instead of none as I would have expected).
I worked around it by specifying 0 insertions/deletions but I thought you might still want to look into that.

**Comment by yunfeiguo** [comment]
Hi @MagdalenaMu 

Typically some number of indels are expected in each genome.  While 500 might not be appropriate for every case, we need to put some positive integer as default. Thanks.
