### ISSUE TITLE
Current install instructions

### ISSUE THREAD

**Issue by Phillip-a-richmond** [bioinform/varsim#207]
Hello,

I'd like to install VarSim in it's most up-to-date form, and would like to have it from a reproducible release.  My install failed on release 0.8.4 with that build.sh script, hanging at this position:

Requirement already satisfied: setuptools in ./miniconda2/lib/python2.7/site-packages (from pyvcf==0.6.8) (41.0.1)
Installing collected packages: pyvcf
Successfully installed pyvcf-0.6.8
+ /project/dri-wasserman/TOOLS/VarSim/opt/miniconda2/bin/python /project/dri-wasserman/TOOLS/VarSim/opt/miniconda2/bin/conda install --yes -c daler pybedtools=0.7.2 bedtools=2.25.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / ^Z

It hung there with a messed up environment for a long time without completing. 

I'm wondering if there was a patch/fix for this, and if a functional 0.8.5 could be released, one that installs when calling build.sh.

Also, I've noticed the documentation went through an overhaul. Is there a timeline for when that will be released as well? I'd like to package VarSim with another tool for quick deployment, so maybe I need to go back to earlier versions of the release? Which was the one that is simple and functional?

Thanks for the tool, it's very useful!

Cheers,
Phil

**Comment by Phillip-a-richmond** [comment]
Forked and fixed my own problem. Had issue with local conda install + curses lib for samtools.

**Comment by marghoob** [comment]
Thanks @Phillip-a-richmond . Would your fix be helpful to include in VarSim?

**Comment by yunfeiguo** [comment]
Hi @Phillip-a-richmond 

Thanks for reporting. Your fix looks really neat (https://github.com/bioinform/varsim/compare/master...Phillip-a-richmond:master).

For deployment, please use the latest VarSim.
