### ISSUE TITLE
Simulating CNV, STR, MEI

### ISSUE THREAD

**Issue by Phillip-a-richmond** [bioinform/varsim#214]
Hello,
In the simulation of CNVs, STRs, and MEIs, does VarSim accept extra user-input VCFs in format v4.2? Specifically asking because in the past, to sim a CNV, I'd create an indel-like VCF, with ref or alt being a very long sequence (length of the CNV, for example). 

I'm wondering if instead of that, for these SVs that it will accept the <DEL> format described here:

https://samtools.github.io/hts-specs/VCFv4.2.pdf (top of page 3, page 11). 

Cheers,
Phil

**Comment by yunfeiguo** [comment]
Hi @Phillip-a-richmond 

Yes, for example: https://github.com/bioinform/varsim/blob/master/src/test/resources/DuplicationTest/input.vcf

**Comment by yunfeiguo** [comment]
And for copy numbers less than 1 for each haplotype, they can be specified as deletions.

**Comment by Phillip-a-richmond** [comment]
Thanks!
