### ISSUE TITLE
Varsim is only generating the `RandVCF2VCF.err` file and the out directory is empty

### ISSUE THREAD

**Issue by ranijames** [bioinform/varsim#220]
Dear All,

Thanks for the Varsam tool. I am using the tool using `All_20180418.vcf` with all other paramter mentioned in the http://bioinform.github.io/varsim/ tutorial. All the other input are also same as the tutorial page. I am runing the tool since 4 hours, all it generated until now is the `RandVCF2VCF.err` file in the `log` directory. The file in `out` directory is empty so far. The tool is still runing. However, I wanna make sure that I doing it right. 

The head of `RandVCF2VCF.err` looks like,
```
14 Oct 2019 13:31:41,541  INFO [main] (VCFparser.java:53): Reading All_20180418.vcf
14 Oct 2019 13:31:41,565  WARN [main] (VCFparser.java:195): Unrecognized phasing '.'.
14 Oct 2019 13:31:41,578  WARN [main] (VCFparser.java:195): Unrecognized phasing '.'.
14 Oct 2019 13:31:41,578  WARN [main] (VCFparser.java:195): Unrecognized phasing '.'.
14 Oct 2019 13:31:41,579  WARN [main] (VCFparser.java:195): Unrecognized phasing '.'.
14 Oct 2019 13:31:41,579  WARN [main] (VCFparser.java:195): Unrecognized phasing '.'
```
and tail looks like,

```
14 Oct 2019 16:24:48,854  WARN [main] (VCFparser.java:743): Returned null variant for line 5	142351770	rs1321417959	A	.	.	.	RS=1321417959;RSPOS=142351771;dbSNPBuildID=151;SSR=0;SAO=0;VP=0x050000080005000002000200;GENEINFO=SPRY4-AS1:101926941;WGT=1;VC=DIV;INT;ASP
14 Oct 2019 16:24:48,854  WARN [main] (VCFparser.java:364): ALT column is malformated: Found illegal character: 46
Offending line: 5	142351805	rs1206923646	A	.	.	.	RS=1206923646;RSPOS=142351806;dbSNPBuildID=151;SSR=0;SAO=0;VP=0x050000080005000002000200;GENEINFO=SPRY4-AS1:101926941;WGT=1;VC=DIV;INT;ASP
14 Oct 2019 16:24:48,854  WARN [main] (VCFparser.java:743): Returned null variant for line 5	142351805	rs1206923646	A	.	.	.	RS=1206923646;RSPOS=142351806;dbSNPBuildID=151;SSR=0;SAO=0;VP=0x050000080005000002000200;GENEINFO=SPRY4-AS1:101926941;WGT=1;VC=DIV;INT;ASP
14 Oct 2019 16:24:48,854  WARN [main] (VCFparser.java:364): ALT column is malformated: Found illegal character: 46
Offending line: 5	142351817	rs1302258236	A

```

The command I used,
```
module load varsim
varsim.py --vc_in_vcf All_20180418.vcf --sv_insert_seq insert_seq.txt --sv_dgv GRCh37_hg19_supportingvariants_2013-07-23.txt --reference hs37d5.fa --id simu --read_length 100 --vc_num_snp 3000000 --vc_num_ins 100000 --vc_num_del 100000 --vc_num_mnp 50000 --vc_num_complex 50000 --sv_num_ins 2000 --sv_num_del 2000 --sv_num_dup 200 --sv_num_inv 1000 --sv_percent_novel 0.01 --vc_percent_novel 0.01 --mean_fragment_size 350 --sd_fragment_size 50 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 --sv_max_length_lim 1000000 --nlanes 5 --total_coverage 1 --simulator_executable ART/art_bin_VanillaIceCream/art_illumina --out_dir out --log_dir log --work_dir work --simulator art
```
Any suggestion/help would be appreciated.

**Comment by yunfeiguo** [comment]
Hi @ranijames the logs and commands look okay to me. One thing is please make sure `ART/art_bin_VanillaIceCream/art_illumina` is the correct path. The example in `quickstart` might be a bit slow, let me whether we can create an even smaller example.

**Comment by yunfeiguo** [comment]
Yeah, that should work.

**Comment by yunfeiguo** [comment]
Hi @ranijames if you want, you can try this example https://github.com/bioinform/varsim/tree/fix_test (`git checkout fix_test` in your varsim folder) which should be much faster than the original example.

**Comment by ranijames** [comment]
@yunfeiguo Thanks for that information! My first test with a single chromosome is finished now. I want to do the secondary analysis using BWA_MEM and haplotype caller(GATK), my question is there are many `lane*.read*.fq.gz` files and `simu.fa` file. I wanna be sure so the `simu.fa` should be the reference and `lane*.read*.fq.gz` are input fasta file for the alignment, isnt?

**Comment by ranijames** [comment]
@yunfeiguo Thanks for that. Yes, I tried on one chromosome and it was pretty fast. I now multiple fasta files and

**Comment by yunfeiguo** [comment]
Hi @ranijames `lane*fq.gz` are the reads, but `simu.fa` is the ground truth sequence (aka perturbed genome), aligner should use standard reference genome (e.g. `GRCh37`).

**Comment by ranijames** [comment]
@yunfeiguo Thanks for the reply and clarification. May I know where can I find the description for the supporting variants(insert_seq.txt) and the insert sequences(GRCh37_hg19_supportingvariants_2013-07-23.txt) used in the tutorial example?
