### ISSUE TITLE
How to restrict the scope of read generation

### ISSUE THREAD

**Issue by fardokhtsadat** [bioinform/varsim#267]
Hello,
I would like to generate synthetic reads for a given reference genome, but I would like to further restrict the scope to generate reads for specific regions in the genome. 
I have checked the manual of the tool, but I cannot find an argument for providing a regions file (BED file) to restrict the scope of read-generation to certain regions. How can this goal be achieved using VarSim?

**Comment by yunfeiguo** [comment]
Hi @fardokhtsadat you need to run `generate_small_test_ref.py` first to restrict the VCF and reference to region of interest and then use the restricted reference and VCF (DGV and random sampling in VCF not supported) to generate simulated reads. For example
```
../../opt/miniconda2/bin/python ../../generate_small_test_ref.py --regions small.bed --vcfs HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz --outdir small_ref_out --reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta
../../varsim.py --reference small_ref_out/ref.fa --id simu --read_length 100 --disable_rand_vcf --disable_rand_dgv --vcfs small_ref_out/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz --mean_fragment_size 350 --sd_fragment_size 50 --nlanes 3 --total_coverage 1 --java_max_mem 50g --lift_ref --simulator_executable ../../opt/ART/art_bin_VanillaIceCream/art_illumina --out_dir out --log_dir log --work_dir work --simulator art
```

This is the output expected:
```
├── out
│   ├── HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz.stats
│   ├── lane0.read1.fq.gz
│   ├── lane0.read2.fq.gz
│   ├── lane1.read1.fq.gz
│   ├── lane1.read2.fq.gz
│   ├── lane2.read1.fq.gz
│   ├── lane2.read2.fq.gz
│   ├── lifted
│   │   ├── truth.map
│   │   ├── truth.vcf.gz
│   │   └── truth.vcf.gz.tbi
│   ├── simu.fa
│   ├── simu.map
│   ├── simu.truth.vcf
│   ├── simu.truth.vcf.stats
│   └── vcf2diploid.out
└── small_ref_out
    ├── HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz
    ├── HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz.tbi
    ├── ref.dict
    ├── ref.fa
    └── ref.fa.fai
```

**Comment by fardokhtsadat** [comment]
@yunfeiguo Thank you for your quick response. You mentioned that DGV is not supported. Does this mean that I cannot create synthetic reads for structural variants?

My main usage is to generate synthetic reads for structural variants given a vcf file. I can see that the coverage has to be specified when creating the synthetic reads. However, if coverage is set to for example 70 then all SVs (both deletions and duplications) will have the same covearge. How can this issue be resolved?

**Comment by yunfeiguo** [comment]
If you want to restrict simulation by providing a BED file, then DGV is not supported. A workaround is put the SVs that you want to simulate into a VCF and provide the SV VCF to `generate_small_test_ref.py`.

If there's a deletion in the simulated genome, then coverage at the deletion locus will drop (depending on what the deletion looks like). Coverage specified on commandline is about average depth, not for every locus in the genome.

**Comment by fardokhtsadat** [comment]
Thank you very much for the information.
