### ISSUE TITLE
duplicated read names

### ISSUE THREAD

**Issue by thirtyeggs** [bioinform/varsim#30]
Hello,

I generated reads using human chromosome 9, and it seems that some reads have the the identical names like:
9-120771251-I-:9-120771251-I:::::::::::28138426:0
I can give different names by myself but I am afraid that changing read names disables varsim's capability of evaluating alignments (correct me if I am wrong). It happened both in the germline mode and in the somatic mode. Could you solve this problem?

Thanks,
Yun

**Comment by johnmu** [comment]
I checked with @marghoob and there is already a read identifier in the read name. In your example, that would be `28138426`.

Do you see the duplicate names in the FASTQ's or the BAM's after alignment?

**Comment by thirtyeggs** [comment]
In the FASTQ files.
I uploaded my data sets here: https://drive.google.com/folderview?id=0B_r_jotTj8w9fkt6bHQyZkVpblpqVXFpQVpvMEhacWFVUDhVSG5GOF8xLXh3OHBxX0dGdDA&usp=sharing

The command line options are:
export dbsnp_vcf=/home/yunheo1/data/human/2015-04-30.icgc-tcga-dream/vcf/for-new-alignment/dbsnp_138.b37.chr9.vcf
export cosmic_vcf=/home/yunheo1/data/human/2015-04-30.icgc-tcga-dream/vcf/for-new-alignment/cosmic.v72.grch37.chr9.vcf.gz
export ref_fasta=/home/yunheo1/data/human/2015-04-30.icgc-tcga-dream/reference/for-new-alignment/separated/9.fasta
export insert_seq=${varsim_dir}/data/insert_seq.txt
export dgv_annotation=${varsim_dir}/data/GRCh37_hg19_supportingvariants_2013-07-23.chr9.txt
export out_dir=/home/tmp/yunheo1/output/varsim/human/2015-05-02.chr9.varsim/2015-05-01
export num_threads=16
export tmp_dir=/dev/shm

# normal
export normal_coverage=40.0
export normal_read_length=100
export normal_mean_frag_size=400
export normal_sd_frag_size=40
export normal_prefix=normal
export normal_num_lanes=1
export normal_percent_novel=0.01
export normal_sex=MALE
export normal_vc_min_length=0
export normal_vc_max_length=49
export normal_sv_min_length=50
export normal_sv_max_length=1000000
export normal_truth_vcf=

# for human chr9
# 5% of the above numbers
export normal_vc_num_snp=150000
export normal_vc_num_ins=5000
export normal_vc_num_del=5000
export normal_vc_num_mnp=2500
export normal_vc_num_complex=2500
export normal_sv_num_ins=100
export normal_sv_num_del=100
export normal_sv_num_dup=10
export normal_sv_num_inv=50

 run varsim
${varsim_dir}/varsim.py \
     --seed                 0 \
     --sex                  $normal_sex \
     --vc_in_vcf            $dbsnp_vcf \
     --sv_insert_seq        $insert_seq \
     --sv_dgv               $dgv_annotation \
     --reference            $ref_fasta \
     --read_length          $normal_read_length \
     --total_coverage       $normal_coverage \
     --mean_fragment_size   $normal_mean_frag_size \
     --sd_fragment_size     $normal_sd_frag_size \
     --nlanes               $normal_num_lanes \
     --simulator            art \
     --simulator_executable ${art_dir}/art_illumina \
     --art_options          "-M -ef -sam -ss HS25" \
     --id                   $normal_prefix \
     --vc_num_snp           $normal_vc_num_snp \
     --vc_num_ins           $normal_vc_num_ins \
     --vc_num_del           $normal_vc_num_del \
     --vc_num_mnp           $normal_vc_num_mnp \
     --vc_num_complex       $normal_vc_num_complex \
     --vc_percent_novel     $normal_percent_novel \
     --vc_min_length_lim    $normal_vc_min_length \
     --vc_max_length_lim    $normal_vc_max_length \
     --sv_num_ins           $normal_sv_num_ins \
     --sv_num_del           $normal_sv_num_del \
     --sv_num_dup           $normal_sv_num_dup \
     --sv_num_inv           $normal_sv_num_inv \
     --sv_percent_novel     $normal_percent_novel \
     --sv_min_length_lim    $normal_sv_min_length \
     --sv_max_length_lim    $normal_sv_max_length \
     --out_dir              ${out_dir}/${normal_prefix}/out \
     --log_dir              ${out_dir}/${normal_prefix}/log \
     --work_dir             ${out_dir}/${normal_prefix}/work

**Comment by thirtyeggs** [comment]
I have an additional suggestion. Tumor reads can be made by mixing some normal lanes and some tumor lanes. Therefore, it would be possible that reads from a normal lane and a tumor lane have the same name. I hope a new version also prevent this.
Thank you!

**Comment by johnmu** [comment]
Yes, that is what I feel is the issue too. I will get back to you on this next week.

**Comment by thirtyeggs** [comment]
Thanks, John. It would be also helpful if two reference sequence names (paternal and maternal) of normal samples could be differentiated from those of tumor samples.

**Comment by johnmu** [comment]
Hi Yun, sorry for the delay. I had some time to think about this and one easy solution will be to use different seeds for each simulation using the `--seed` parameter. This should ensure that the datasets are unique. 

With regards to your suggestion about the reference names. Do you mind submitting it as a new issue so I can track it? Thanks!

**Comment by thirtyeggs** [comment]
Hi John,
We have two issues: 1) duplicated read names in a single varsim run 2) potential duplicated read names between normal reads and tumor reads.
Do you think that the above two issues can be resolved by using different seeds? Can you explain how the seed affect the read names?
BTW, I will create another issue for the reference name.
Thank you for your help!

**Comment by johnmu** [comment]
Sorry, so for the example you gave me. There are duplicated read names in a single run? Let me try to reproduce...




The read name essentially encodes the alignment location of the reads and an index that should be unique within each thread(lane). It is possible to have duplicates, but it would be unlikely.




Setting a different seed should fix case number 2



--John Mu

**Comment by johnmu** [comment]
I am trying to reproduce this, however it appears that `-M` is not a valid parameter for ART. What version of ART are you using?

**Comment by thirtyeggs** [comment]
I am using the latest version: ART-ChocolateCherries-03-09-2015. "-ss" is used to specify the sequencing system. HS25 means Illumina HiSeq 2500.

**Comment by johnmu** [comment]
Thanks, I see now. Those options came in the new version.

**Comment by johnmu** [comment]
I am able to replicate the duplicated read names! Let me have a look at why this is happening....

**Comment by johnmu** [comment]
ok, I found out why. one read is from maternal chromosome and one is from paternal chromosome. Let me fix this.

**Comment by thirtyeggs** [comment]
That is a good news. Thank you for your effort!

**Comment by johnmu** [comment]
this https://github.com/bioinform/varsim/pull/32 should fix it. I'll merge this and make a release after a few more new things.

**Comment by thirtyeggs** [comment]
Hi John,

 

Thank you very much for your effort. Can I ask when you expect to release a new version?

This is for me to decide which version (a new branch or a new future release in the main branch) I have to use.

 

Thanks,

Yun

**Comment by johnmu** [comment]
Hi Yun, Most likely this week.

**Comment by thirtyeggs** [comment]
I tried to build varsim using the latest code but I got the following error message. I am not familiar with maven so I cannot understand why it happens:


[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building varsim 0.5.2
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/broad/tribble/tribble/46/tribble-46.pom
[WARNING] The POM for org.broad.tribble:tribble:jar:46 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
Downloaded: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom (12 KB at 54.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom (57 KB at 306.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom (15 KB at 171.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/broad/tribble/tribble/46/tribble-46.jar
Downloading: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
Downloaded: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar (278 KB at 565.2 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.490 s
[INFO] Finished at: 2015-05-20T14:03:23-05:00
[INFO] Final Memory: 27M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project varsim: Could not resolve dependencies for project com.bina.varsim:varsim:jar:0.5.2: Could not find artifact org.broad.tribble:tribble:jar:46 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by johnmu** [comment]
Please remove that dependency. It is not needed anymore. We used to have an
internal copy of that.

On Wed, May 20, 2015 at 12:17 PM, thirtyeggs <notifications@github.com>
wrote:

> I tried to build varsim using the latest code but I got the following
> error message. I am not familiar with maven so I cannot understand why it
> happens:
>
> [INFO] Scanning for projects...
> [INFO]
>
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Building varsim 0.5.2
> [INFO]
> ------------------------------------------------------------------------
> Downloading:
> https://repo.maven.apache.org/maven2/org/broad/tribble/tribble/46/tribble-46.pom
> [WARNING] The POM for org.broad.tribble:tribble:jar:46 is missing, no
> dependency information available
> Downloading:
> https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
> Downloaded:
> https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
> (12 KB at 54.8 KB/sec)
> Downloading:
> https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom
> Downloaded:
> https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom
> (57 KB at 306.6 KB/sec)
> Downloading:
> https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom
> Downloaded:
> https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom
> (15 KB at 171.0 KB/sec)
> Downloading:
> https://repo.maven.apache.org/maven2/org/broad/tribble/tribble/46/tribble-46.jar
> Downloading:
> https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
> Downloaded:
> https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
> (278 KB at 565.2 KB/sec)
> [INFO]
> ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Total time: 4.490 s
> [INFO] Finished at: 2015-05-20T14:03:23-05:00
> [INFO] Final Memory: 27M/1963M
> [INFO]
> ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project varsim: Could not resolve
> dependencies for project com.bina.varsim:varsim:jar:0.5.2: Could not find
> artifact org.broad.tribble:tribble:jar:46 in central (
> https://repo.maven.apache.org/maven2) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the
> -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions,
> please read the following articles:
> [ERROR] [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioinform/varsim/issues/30#issuecomment-104002272>.
>



-- 

*John Mu, PhD*
*Research Engineer, Data Science*
*Bina Technologies <http://www.bina.com>*, part of Roche Sequencing

**Comment by thirtyeggs** [comment]
I see. I removed line 91-95 in pom.xml and it worked.
Thanks!

**Comment by johnmu** [comment]
https://github.com/bioinform/varsim/releases/tag/v0.5.2 Here's a release if you still need it.
