### ISSUE TITLE
Support art_SOLiD reads

### ISSUE THREAD

**Issue by wx115** [bioinform/varsim#34]
Sorry if I'm wrong, but I cannot find support for art_SOLiD reads in the current VarSim. The .fq file output from art_SOLiD is different from art_illumina. art_SOLiD uses color codes instead of the nucleotides ACGT. Also there is no .aln file, but only .map file output from the reads simulator. Does the current VarSim support art_SOLiD reads? How to perform fastqLiftOver on art_SOLiD reads? Thank you.

**Comment by johnmu** [comment]
Sorry, unfortunately we do not support SOLiD reads and do not have plans to support it in the future.

**Comment by wx115** [comment]
Thanks for the reply. Do you support any other sequencers, or do you have any plan to support other sequencers in the future?

**Comment by johnmu** [comment]
We have some plans to support pacbio, but that is it for now.
