### ISSUE TITLE
Produce simulated data in certain intervals?

### ISSUE THREAD

**Issue by choosehappy** [bioinform/varsim#44]
For example, accept a bed file as a command line parameter, and only produce reads within the ranges specified in the bed file. 

I'm thinking about this as a means of producing exome read data. Currently its possible to use varsim to simulate the entire genome, and then use a bed file to extract solely exon regions. Typically, though, exome data is sequenced at 100x, so producing the whole genome at 100x to subset it becomes a bit unwieldy. 

Thoughts?

**Comment by marghoob** [comment]
We have been considering incorporating exome simulators in VarSim, since exome simulation is much more than simply generating reads from specific intervals. If you know of any good exome simulator, please let us know.

**Comment by choosehappy** [comment]
The only i currently know of is Wessim:

http://www.ncbi.nlm.nih.gov/pubmed/23413434
http://sak042.github.io/Wessim/

**Comment by marghoob** [comment]
A simple targeted simulation is supported in VarSim now using the `varsim_multi.py` script.
