### ISSUE TITLE
Multiple reads with same name

### ISSUE THREAD

**Issue by Phillip-a-richmond** [bioinform/varsim#49]
Hello,
I've been using your tool, and it seems that when I simulate reads (following the default example you provided [here](http://bioinform.github.io/varsim/), I'm running into an error with identical read names.  It seems this should have been cleared up in the past, but it isn't.  Here's my command:

/opt/tools/varsim/varsim.py --vc_in_vcf /mnt/data/Benchmark/All_20160527.vcf --sv_insert_seq /opt/tools/varsim/insert_seq.txt \
 --sv_dgv /opt/tools/varsim/GRCh37_hg19_supportingvariants_2013-07-23.txt \
 --reference /opt/tools/varsim/hs37d5.fa --id simu --read_length 100 --vc_num_snp 3000000 --vc_num_ins 100000 \
 --vc_num_del 100000 --vc_num_mnp 50000 --vc_num_complex 50000 --sv_num_ins 2000 \
 --sv_num_del 2000 --sv_num_dup 200 --sv_num_inv 1000 --sv_percent_novel 0.01 \
 --vc_percent_novel 0.01 --mean_fragment_size 350 --sd_fragment_size 50 \
 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 \
 --sv_max_length_lim 1000000 --nlanes 5 --total_coverage 50 \
 --simulator_executable /opt/tools/ART/art_illumina --out_dir /mnt/data/Benchmark/TestFromQueue \
 --log_dir /mnt/data/Benchmark/logFromQueue --work_dir /mnt/data/Benchmark/workFromQueue \
 --simulator art  \

I'm seeing this error whenever I try to use the Picard Tools suite:
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  2: 17-126946-I:17-126946-I-:::::::::::2548929:0
	at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:132)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
	at htsjdk.samtools.SamFileValidator$CoordinateSortedPairEndInfoMap.remove(SamFileValidator.java:724)
	at htsjdk.samtools.SamFileValidator.validateMateFields(SamFileValidator.java:465)
	at htsjdk.samtools.SamFileValidator.validateSamRecordsAndQualityFormat(SamFileValidator.java:276)
	at htsjdk.samtools.SamFileValidator.validateSamFile(SamFileValidator.java:199)
	at htsjdk.samtools.SamFileValidator.validateSamFileVerbose(SamFileValidator.java:159)
	at picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:166)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

And by grepping for those reads out of the SAM file:
grep   "17-126946-I:17-126946-I-:::::::::::2548929:0"   file.sam

I get the fact that there are two pairs of reads with the exact same name, but different sequences.
17-126946-I:17-126946-I-:::::::::::2548929:0	97	chr1	45779450	0	38S54M8S	chr3	181289900	0	TCGGTTAAGATACAACATCCAGTTGGTGGCAGCCCAACTGATCTGCCCGCCTCGGCCTCCCAAAGTTTTGGGATTACAGGCGTGAGCCACCATTAGTGTG	@@CFFFFDFGHHHI2IJJFJEJJJJJGJIIGJ?=HI:GJGJH)IJ3-IJDHA?>JJI>ICI=CJAHFC;EEI2ED,DDEDE@EHCDE:DDCDDDD(C>BC	NM:i:0	MD:Z:54	AS:i:54	XS:i:53	RG:Z:BWA_Benchmark
17-126946-I:17-126946-I-:::::::::::2548929:0	145	chr3	181289900	0	33S21M46S	chr1	45779450	0	TTTTTTTTAATAAATAACACATAAAAAAACTATAACAAAATTTTTATTTTTTTTGCATTAAATCTATCCACTAGTATATTATATTTTTTAGTAAATAAAG	D5BD<CD#BDDC>CDD:DI>ADHIDJHC>A.?JJI@8BEJG;JHE)IJCFCDJJ0BJIDJD@GIJHJ?JF@JJJJGJEJJIGFJCGJHG?HHEFFFF@CC	NM:i:0	MD:Z:21	AS:i:21	XS:i:21	RG:Z:BWA_Benchmark
17-126946-I:17-126946-I-:::::::::::2548929:0	97	chr2	133005960	0	66M34S	chr3	90472098	0	GCAAACATCATAAAGTAGTTTCTGAGAGTGCTTCTGTCTAGTTTTTATGCGAAGATATTTCCTTTTCTACCTTAGACCTCAAAAAGCTCTAAATATACAC	@8CFDFFFDHH<H<(JIIJJHJHA<HEJJJJIJJ7EGIDI@IIIIIFDC';IJGI)JJJJJJDJID<;&CF=JBECG5H;5+D(DD,CCEABDD?DFBD&	NM:i:3	MD:Z:23C3A21T16	AS:i:51	XS:i:48	RG:Z:BWA_Benchmark
17-126946-I:17-126946-I-:::::::::::2548929:0	145	chr3	90472098	6	100M	chr2	133005960	0	TCAAAGCGCTCTAAATATCCACTTGCAGATTCTACAAAAAGAGTGTTTCAAAACTGCTCTATCAAAAGGAAGGTTCAACTCTGTGACTTGAATGCACACA	D?C<BBBDD:?CDEDDD@DDE>FD.D>HJJ?HI@IHIBF<DDJ0CE@>FEIF9FC@H@IB>JJ@GIDIJ<EE=IJ?JJI:GFAJJ<IF3HFHFDFFF?@C	NM:i:2	MD:Z:11C74G13	AS:i:90	XS:i:86	RG:Z:BWA_Benchmark

**Comment by marghoob** [comment]
Thanks for bringing this to our attention. We will have a look and get back to you as soon as possible. By the way, which version of VarSim are you using?

**Comment by Phillip-a-richmond** [comment]
Version 0.5.1

**Comment by Phillip-a-richmond** [comment]
Ahh I see you're now on version 6.3.  I'll have my systems admin update versions to see if this error is mitigated.  Or should I stay in the version 5s?

**Comment by marghoob** [comment]
Please give 0.6.3 a try and let me know how it works.

**Comment by Phillip-a-richmond** [comment]
The bug seems to be resolved as I'm not getting any errors now.

Thanks,
Phil
