### ISSUE TITLE
Something strange, multiple SNP matches in true set

### ISSUE THREAD

**Issue by Phillip-a-richmond** [bioinform/varsim#50]
I'm getting this output when comparing my vcf file back to the simu_truth.vcf:

31 Aug 2016 14:35:32,929  INFO [main] (VCFcompare.java:1120): Something strange, multiple SNP matches in true set: 2

It prints out numerous (~100) times.

Any idea what this means, and should I be worried?

My command:
java -jar VarSim.jar vcfcompare -prefix simu  BWA_Benchmark_BWAmem_dupremoved_realigned_v0.1.19mpileup_rmindelIS1.vcf -true_vcf simu.truth.vcf

Thanks,
Phil

**Comment by marghoob** [comment]
Thanks, Phil, let me look into this.

**Comment by marghoob** [comment]
Hi @Phillip-a-richmond can you send me the VCFs you used for the comparison?

**Comment by Phillip-a-richmond** [comment]
@marghoob Yes my VCF file is roughly 400Mb, how do you want me to transfer it to you?  GitHub will only accept 10Mb files.

**Comment by Phillip-a-richmond** [comment]
Ahhh, it looks like the All.vcf that I was using was for the wrong reference genome.  I'll rerun the analysis and if the issue persists then I'll reopen another one.

Sorry!
Phil
