### ISSUE TITLE
Can I use it to generate(simulate) multiple samples into a vcf file?

### ISSUE THREAD

**Issue by CoREse** [bioinform/varsim#52]
I need to generate a lot of samples in a vcf file. Can varsim generate such a vcf file?

**Comment by marghoob** [comment]
Currently, VarSim only generate a single-sample truth VCF.

**Comment by CoREse** [comment]
OK, I see, thanks.

**Comment by CoREse** [comment]
Another question, when the input is given, will varsim generate the same truth vcf every time? Can it generate the truth vcf randomly?

**Comment by hradhakrishnan** [comment]
Hi, had the same question. Does the truth vcf file vary with each run

**Comment by marghoob** [comment]
Yes, VarSim is deterministic should it should generate the same truth VCF every time.
