### ISSUE TITLE
missing maternal.chain

### ISSUE THREAD

**Issue by mmcneill123** [bioinform/varsim#84]
Good morning, 

Thank you for providing public access to this very nice code base. I am currently running into an error, and I'm hoping you can help me get the code working.

I'm running the following command:

sample_name=Variants_Test
vcf_file=/mnt/work/mmcneill/TestData/orig_input_files/S1_R1R2Consensus.vardict.vcf.gz
out_dir=/mnt/work/mmcneill/TestData/outLarge
read_length=150
total_coverage=1000
mean_fragment_size=184
sd_fragment_size=13
prop_het_vcf=0.2
vc_max_length_lim=150
vc_num_snp=1000
vc_num_ins=1000
vc_num_del=1000
vc_num_complex=1000
varsimPath=/mnt/HPC/pub/bin/varsim/
REF=/mnt/HPC/genomicdata/hg19/hg19.fa
simulator_executable=$(which art_illumina)

python2.7 ${varsimPath}varsim.py \
--out_dir ${out_dir} \
--log_dir ${out_dir} \
--reference ${REF} \
--id ${sample_name} \
--simulator_executable ${simulator_executable} \
--varsim_jar ${varsimPath}/VarSim.jar \
--read_length ${read_length} \
--total_coverage ${total_coverage} \
--mean_fragment_size ${mean_fragment_size} \
--sd_fragment_size ${sd_fragment_size} \
--force_five_base_encoding \
--vc_in_vcf ${vcf_file} \
--vc_prop_het ${prop_het_vcf} \
--vc_max_length_lim ${vc_max_length_lim} \
--vc_num_snp ${vc_num_snp} \
--vc_num_ins ${vc_num_ins} \
--vc_num_del ${vc_num_ins} \
--vc_num_complex ${vc_num_complex} \
--art_options "-ss MS --amplicon" \
--disable_rand_dgv

This ran well for a while, but then it generated the following error:
Traceback (most recent call last):
  File "/mnt/HPC/pub/bin/varsim/varsim.py", line 376, in <module>
    with open(os.path.join(args.out_dir, "%s.chain" % (strand))) as strand_chain:
IOError: [Errno 2] No such file or directory: '/mnt/work/mmcneill/TestData/outLarge/maternal.chain'

In the output directory, there are many *.fa, *.map, *.vcf and even merged.chain files. 

Have you seen this error before, and if so, do you know how to fix it? 

Thanks very much for your time. 
Sincerely, 
Matt McNeill

**Comment by marghoob** [comment]
Hi Matt

Which version of VarSim are you using? If possible, could you please checkout the master branch and run build_release.sh to build a VarSim release from the current master? This will require maven to be installed on the system.

Best
Marghoob.

**Comment by mmcneill123** [comment]
Hi Marghoob, 
Thanks very much for the quick reply!
python2.7 varsim.py --version reports v0.6 before and after the update. I updated to master, which found 205 changes. 

After recompiling, I re-ran my command. It ran without errors. Thanks for your help!

Matt
